import type {
  GeneticsKey,
  GrowingKey,
  LocalizedText,
  PlantProfile,
  TaxonomyKey,
  UsageKey,
} from "@/features/kb/plant-profiles"

const dash: LocalizedText = { uk: "—", en: "—", ru: "—" }

function t(uk: string, en: string, ru: string): LocalizedText {
  return { uk, en, ru }
}

function section<K extends string>(
  keys: readonly K[],
  values?: Partial<Record<K, LocalizedText>>
): Record<K, LocalizedText> {
  return Object.fromEntries(
    keys.map((key) => [key, values?.[key] ?? dash])
  ) as Record<K, LocalizedText>
}

const TAXONOMY_KEYS = [
  "family",
  "genus",
  "species",
  "lifeCycle",
  "origin",
  "summary",
] as const satisfies readonly TaxonomyKey[]

const GROWING_KEYS = [
  "plantTime",
  "sowingDepth",
  "light",
  "watering",
  "soil",
  "climate",
  "maturity",
  "yield",
  "seedRate",
  "seedlings",
  "companions",
  "pests",
  "fertilizer",
] as const satisfies readonly GrowingKey[]

const GENETICS_KEYS = [
  "varietyType",
  "pollination",
  "habit",
  "ploidy",
  "traits",
] as const satisfies readonly GeneticsKey[]

const USAGE_KEYS = [
  "purpose",
  "edibleParts",
  "culinary",
  "harvest",
  "storage",
] as const satisfies readonly UsageKey[]

function veg(
  imageUrl: string,
  taxonomy: Partial<Record<TaxonomyKey, LocalizedText>>,
  growing: Partial<Record<GrowingKey, LocalizedText>>,
  genetics: Partial<Record<GeneticsKey, LocalizedText>>,
  usage: Partial<Record<UsageKey, LocalizedText>>
): PlantProfile {
  return {
    imageUrl,
    taxonomy: section(TAXONOMY_KEYS, taxonomy),
    growing: section(GROWING_KEYS, growing),
    genetics: section(GENETICS_KEYS, genetics),
    usage: section(USAGE_KEYS, usage),
  }
}

const solanaceae = t("Пасльонові (Solanaceae)", "Solanaceae", "Паслёновые (Solanaceae)")
const cucurbitaceae = t("Гарбузові (Cucurbitaceae)", "Cucurbitaceae", "Тыквенные (Cucurbitaceae)")
const brassicaceae = t("Капустяні (Brassicaceae)", "Brassicaceae", "Капустные (Brassicaceae)")
const apiaceae = t("Зонтичні (Apiaceae)", "Apiaceae", "Зонтичные (Apiaceae)")
const amaryllidaceae = t("Амарилісові (Amaryllidaceae)", "Amaryllidaceae", "Амариллисовые (Amaryllidaceae)")
const asteraceae = t("Айстрові (Asteraceae)", "Asteraceae", "Астровые (Asteraceae)")
const amaranthaceae = t("Щирицеві (Amaranthaceae)", "Amaranthaceae", "Амарантовые (Amaranthaceae)")
const fabaceae = t("Бобові (Fabaceae)", "Fabaceae", "Бобовые (Fabaceae)")
const poaceae = t("Злакові (Poaceae)", "Poaceae", "Злаковые (Poaceae)")

export const GARDEN_VEGETABLE_PROFILES: Record<string, PlantProfile> = {
  kb_species_solanum_tuberosum: veg(
    "/plants/potato.svg",
    {
      family: solanaceae,
      genus: t("Паслін (Solanum)", "Solanum", "Паслён (Solanum)"),
      species: t("Solanum tuberosum", "Solanum tuberosum", "Solanum tuberosum"),
      lifeCycle: t("Бульбоплід, як однорічна", "Tuber crop grown as an annual", "Клубнеплод, как однолетняя"),
      origin: t("Анди, Південна Америка", "Andes, South America", "Анды, Южная Америка"),
      summary: t("Городня культура з їстівними бульбами.", "Garden crop with edible tubers.", "Огородная культура со съедобными клубнями."),
    },
    {
      yield: t("2–4 кг з куща", "2–4 kg per plant", "2–4 кг с куста"),
      plantTime: t("Квітень–травень, ґрунт >8 °C", "April–May, soil above 8 °C", "Апрель–май, почва >8 °C"),
      maturity: t("70–120 днів", "70–120 days", "70–120 дней"),
      watering: t("Рівномірно, більше в бульбоутворення", "Evenly, more while tubers form", "Равномерно, больше при клубнеобразовании"),
      soil: t("Пухкий суглинок, pH 5.5–6.5", "Loose loam, pH 5.5–6.5", "Рыхлый суглинок, pH 5.5–6.5"),
      climate: t("Прохолодно, без спеки >28 °C", "Cool, avoid heat above 28 °C", "Прохладно, без жары >28 °C"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("Бульба 8–10 см", "Tuber 8–10 cm", "Клубень 8–10 см"),
      seedRate: t("4–6 рослин / м²", "4–6 plants / m²", "4–6 растений / м²"),
      seedlings: t("Пророщені бульби", "Chitted tubers", "Пророщенные клубни"),
      companions: t("Квасоля, кукурудза, чорнобривці", "Bean, corn, marigold", "Фасоль, кукуруза, бархатцы"),
      pests: t("Фітофтора, колорадський жук", "Late blight, Colorado potato beetle", "Фитофтора, колорадский жук"),
      fertilizer: t("Калій, без свіжого гною", "Potassium, no fresh manure", "Калий, без свежего навоза"),
    },
    {
      varietyType: t("Ранні, середні й пізні сорти", "Early, mid and late cultivars", "Ранние, средние и поздние сорта"),
      pollination: t("Комахи; насіння рідко сіють", "Insects; seed is rarely sown", "Насекомые; семена сеют редко"),
      habit: t("Кущ із підземними столонами", "Bush with underground stolons", "Куст с подземными столонами"),
      ploidy: t("Тетраплоїд, 2n = 48", "Tetraploid, 2n = 48", "Тетраплоид, 2n = 48"),
      traits: t("Крохмалисті бульби, вічка", "Starchy tubers with eyes", "Крахмалистые клубни, глазки"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Бульби", "Tubers", "Клубни"),
      culinary: t("Варіння, смаження, запікання", "Boiling, frying, roasting", "Варка, жарка, запекание"),
      harvest: t("Коли бадилля жовтіє", "When haulm yellows", "Когда ботва желтеет"),
      storage: t("Темно, 4–6 °C, сухе", "Dark, 4–6 °C, dry", "Темно, 4–6 °C, сухо"),
    }
  ),
  kb_species_solanum_melongena: veg(
    "/plants/eggplant.svg",
    {
      family: solanaceae,
      genus: t("Паслін (Solanum)", "Solanum", "Паслён (Solanum)"),
      species: t("Solanum melongena", "Solanum melongena", "Solanum melongena"),
      lifeCycle: t("Теплолюбна, як однорічна", "Warmth-loving, grown as annual", "Теплолюбивая, как однолетняя"),
      origin: t("Південна Азія", "South Asia", "Южная Азия"),
      summary: t("Плодова пасльонова для городу й теплиці.", "Fruiting nightshade for garden and greenhouse.", "Плодовая паслёновая для огорода и теплицы."),
    },
    {
      yield: t("2–4 кг з куща", "2–4 kg per plant", "2–4 кг с куста"),
      plantTime: t("Травень після заморозків", "May after frost", "Май после заморозков"),
      maturity: t("100–140 днів від сходів", "100–140 days from sprouting", "100–140 дней от всходов"),
      watering: t("Регулярно, не пересушувати", "Regularly, do not dry out", "Регулярно, не пересушивать"),
      soil: t("Родючий, теплий, pH 6.0–7.0", "Fertile, warm, pH 6.0–7.0", "Плодородный, тёплый, pH 6.0–7.0"),
      climate: t("Тепло, 22–28 °C", "Warm, 22–28 °C", "Тепло, 22–28 °C"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1 см", "1 cm", "1 см"),
      seedRate: t("3–4 рослини / м²", "3–4 plants / m²", "3–4 растения / м²"),
      seedlings: t("Розсада 60–70 днів", "60–70 day seedlings", "Рассада 60–70 дней"),
      companions: t("Перець, базилік, квасоля", "Pepper, basil, bean", "Перец, базилик, фасоль"),
      pests: t("Колорадський жук, попелиця, фітофтора", "Colorado beetle, aphids, late blight", "Колорадский жук, тля, фитофтора"),
      fertilizer: t("Калій і фосфор у плодоношення", "Potassium and phosphorus while fruiting", "Калий и фосфор в плодоношение"),
    },
    {
      varietyType: t("Сорти за формою й кольором плоду", "Cultivars by fruit shape and color", "Сорта по форме и цвету плода"),
      pollination: t("Самозапильна, допомагають джмелі", "Self-pollinating, bumblebees help", "Самоопыляемая, помогают шмели"),
      habit: t("Кущ 50–90 см", "Bush 50–90 cm", "Куст 50–90 см"),
      ploidy: t("Диплоїд, 2n = 24", "Diploid, 2n = 24", "Диплоид, 2n = 24"),
      traits: t("Глянцеві плоди, гіркота при перезріванні", "Glossy fruit, bitter if overripe", "Глянцевые плоды, горечь при перезревании"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Недозрілі плоди", "Immature fruit", "Незрелые плоды"),
      culinary: t("Смаження, ікра, гриль", "Frying, spread, grilling", "Жарка, икра, гриль"),
      harvest: t("Поки шкірка блищить", "While skin is glossy", "Пока кожица блестит"),
      storage: t("Коротко, 10–12 °C", "Briefly, 10–12 °C", "Кратко, 10–12 °C"),
    }
  ),
  kb_species_cucurbita_pepo: veg(
    "/plants/zucchini.svg",
    {
      family: cucurbitaceae,
      genus: t("Гарбуз (Cucurbita)", "Cucurbita", "Тыква (Cucurbita)"),
      species: t("Cucurbita pepo", "Cucurbita pepo", "Cucurbita pepo"),
      lifeCycle: t("Однорічна", "Annual", "Однолетняя"),
      origin: t("Мезоамерика", "Mesoamerica", "Мезоамерика"),
      summary: t("Кабачок і патисон — швидкі городні плоди.", "Zucchini and pattypan — fast garden fruits.", "Кабачок и патиссон — быстрые огородные плоды."),
    },
    {
      yield: t("4–8 кг з куща", "4–8 kg per plant", "4–8 кг с куста"),
      plantTime: t("Травень–червень", "May–June", "Май–июнь"),
      maturity: t("45–60 днів", "45–60 days", "45–60 дней"),
      watering: t("Рясно в спеку", "Generously in heat", "Обильно в жару"),
      soil: t("Родючий, вологий", "Fertile, moist", "Плодородный, влажный"),
      climate: t("Тепло, без заморозків", "Warm, frost-free", "Тепло, без заморозков"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("2–3 см", "2–3 cm", "2–3 см"),
      seedRate: t("1–2 рослини / м²", "1–2 plants / m²", "1–2 растения / м²"),
      seedlings: t("Прямий посів або розсада 20 днів", "Direct sow or 20-day seedlings", "Прямой посев или рассада 20 дней"),
      companions: t("Кукурудза, настурція, цибуля", "Corn, nasturtium, onion", "Кукуруза, настурция, лук"),
      pests: t("Борошниста роса, попелиця", "Powdery mildew, aphids", "Мучнистая роса, тля"),
      fertilizer: t("Компост, калій у плодоношення", "Compost, potassium while fruiting", "Компост, калий в плодоношение"),
    },
    {
      varietyType: t("Кущові й плетисті; кабачок, патисон", "Bush and vining; zucchini, pattypan", "Кустовые и плетистые; кабачок, патиссон"),
      pollination: t("Комахи", "Insect-pollinated", "Насекомые"),
      habit: t("Кущ або коротка ліана", "Bush or short vine", "Куст или короткая лиана"),
      ploidy: t("Диплоїд, 2n = 40", "Diploid, 2n = 40", "Диплоид, 2n = 40"),
      traits: t("Молоді плоди найсмачніші", "Young fruit tastes best", "Молодые плоды самые вкусные"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Молоді плоди, інколи квітки", "Young fruit, sometimes flowers", "Молодые плоды, иногда цветки"),
      culinary: t("Тушкування, оладки, ікра", "Stewing, fritters, spread", "Тушение, оладьи, икра"),
      harvest: t("15–20 см, регулярно", "15–20 cm, regularly", "15–20 см, регулярно"),
      storage: t("Коротко в холоді", "Briefly chilled", "Кратко в холоде"),
    }
  ),
  kb_species_cucurbita_maxima: veg(
    "/plants/pumpkin.svg",
    {
      family: cucurbitaceae,
      genus: t("Гарбуз (Cucurbita)", "Cucurbita", "Тыква (Cucurbita)"),
      species: t("Cucurbita maxima", "Cucurbita maxima", "Cucurbita maxima"),
      lifeCycle: t("Однорічна баштанна", "Annual cucurbit", "Однолетняя бахчевая"),
      origin: t("Південна Америка", "South America", "Южная Америка"),
      summary: t("Великоплідний гарбуз для каші й зберігання.", "Large pumpkin for porridge and storage.", "Крупноплодная тыква для каши и хранения."),
    },
    {
      yield: t("1–3 плоди з рослини", "1–3 fruits per plant", "1–3 плода с растения"),
      plantTime: t("Травень", "May", "Май"),
      maturity: t("90–120 днів", "90–120 days", "90–120 дней"),
      watering: t("Рясно до наливу плодів", "Generously until fruit fill", "Обильно до налива плодов"),
      soil: t("Родючий легкий суглинок", "Fertile light loam", "Плодородный лёгкий суглинок"),
      climate: t("Тепло, довге літо", "Warm, long summer", "Тепло, длинное лето"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("3–4 см", "3–4 cm", "3–4 см"),
      seedRate: t("1 рослина / 1–2 м²", "1 plant / 1–2 m²", "1 растение / 1–2 м²"),
      seedlings: t("Прямий посів у лунки", "Direct sow in hills", "Прямой посев в лунки"),
      companions: t("Кукурудза, квасоля", "Corn, bean", "Кукуруза, фасоль"),
      pests: t("Борошниста роса, слимаки", "Powdery mildew, slugs", "Мучнистая роса, слизни"),
      fertilizer: t("Органіка в лунку, калій пізніше", "Organics in the hill, potassium later", "Органика в лунку, калий позже"),
    },
    {
      varietyType: t("Столові сорти різної форми", "Table cultivars of various shapes", "Столовые сорта разной формы"),
      pollination: t("Комахи, роздільностатеві квітки", "Insects, unisexual flowers", "Насекомые, раздельнополые цветки"),
      habit: t("Довга ліана", "Long vine", "Длинная лиана"),
      ploidy: t("Диплоїд, 2n = 40", "Diploid, 2n = 40", "Диплоид, 2n = 40"),
      traits: t("Товста м’якоть, тверда шкірка", "Thick flesh, hard rind", "Толстая мякоть, твёрдая корка"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("М’якоть, насіння", "Flesh, seeds", "Мякоть, семена"),
      culinary: t("Каша, запікання, насіння", "Porridge, roasting, seeds", "Каша, запекание, семена"),
      harvest: t("Коли плодоніжка корковіє", "When the stem corks", "Когда плодоножка пробковеет"),
      storage: t("Сухо, 10–15 °C, місяцями", "Dry, 10–15 °C, for months", "Сухо, 10–15 °C, месяцами"),
    }
  ),
  kb_species_brassica_oleracea_capitata: veg(
    "/plants/cabbage.svg",
    {
      family: brassicaceae,
      genus: t("Капуста (Brassica)", "Brassica", "Капуста (Brassica)"),
      species: t("Brassica oleracea var. capitata", "Brassica oleracea var. capitata", "Brassica oleracea var. capitata"),
      lifeCycle: t("Дворічна, вирощують як однорічну", "Biennial grown as an annual", "Двулетняя, выращивают как однолетнюю"),
      origin: t("Середземномор’я, Європа", "Mediterranean, Europe", "Средиземноморье, Европа"),
      summary: t("Головчаста капуста для свіжого столу й квашення.", "Heading cabbage for fresh use and fermenting.", "Кочанная капуста для стола и квашения."),
    },
    {
      yield: t("2–5 кг з рослини", "2–5 kg per plant", "2–5 кг с растения"),
      plantTime: t("Квітень–червень, розсада", "April–June, transplants", "Апрель–июнь, рассада"),
      maturity: t("70–140 днів", "70–140 days", "70–140 дней"),
      watering: t("Рівномірно, не пересихати", "Evenly, do not dry out", "Равномерно, не пересыхать"),
      soil: t("Родючий суглинок, pH 6.5–7.2", "Fertile loam, pH 6.5–7.2", "Плодородный суглинок, pH 6.5–7.2"),
      climate: t("Прохолодно, без тривалої спеки", "Cool, avoid long heat", "Прохладно, без долгой жары"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1–1.5 см", "1–1.5 cm", "1–1.5 см"),
      seedRate: t("4–6 рослин / м²", "4–6 plants / m²", "4–6 растений / м²"),
      seedlings: t("Розсада 40–50 днів", "40–50 day seedlings", "Рассада 40–50 дней"),
      companions: t("Кріп, буряк, цибуля", "Dill, beet, onion", "Укроп, свёкла, лук"),
      pests: t("Капустяна міль, блішки, кила", "Cabbage moth, flea beetles, clubroot", "Капустная моль, блошки, кила"),
      fertilizer: t("Азот на старті, калій у зав’язування", "Nitrogen early, potassium at heading", "Азот на старте, калий при завязывании"),
    },
    {
      varietyType: t("Ранні, середні, пізні; біла й червона", "Early, mid, late; white and red", "Ранние, средние, поздние; белая и красная"),
      pollination: t("Перехресне, комахи", "Cross-pollinated by insects", "Перекрёстное, насекомые"),
      habit: t("Розетка, щільна головка", "Rosette with a dense head", "Розетка, плотный кочан"),
      ploidy: t("Диплоїд, 2n = 18", "Diploid, 2n = 18", "Диплоид, 2n = 18"),
      traits: t("Головка з листя, дворічне цвітіння", "Leaf head, flowers in year two", "Кочан из листьев, цветение на второй год"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Головка", "Head", "Кочан"),
      culinary: t("Салат, борщ, квашення", "Salad, borscht, fermenting", "Салат, борщ, квашение"),
      harvest: t("Коли головка щільна", "When the head is firm", "Когда кочан плотный"),
      storage: t("Пізні сорти — холодно й волого", "Late types: cold and humid", "Поздние сорта — холодно и влажно"),
    }
  ),
  kb_species_brassica_oleracea_italica: veg(
    "/plants/broccoli.svg",
    {
      family: brassicaceae,
      genus: t("Капуста (Brassica)", "Brassica", "Капуста (Brassica)"),
      species: t("Brassica oleracea var. italica", "Brassica oleracea var. italica", "Brassica oleracea var. italica"),
      lifeCycle: t("Дворічна, як однорічна", "Biennial grown as an annual", "Двулетняя, как однолетняя"),
      origin: t("Середземномор’я, Італія", "Mediterranean, Italy", "Средиземноморье, Италия"),
      summary: t("Їстівні суцвіття броколі для прохолодного сезону.", "Edible broccoli heads for the cool season.", "Съедобные соцветия брокколи для прохладного сезона."),
    },
    {
      yield: t("0.4–0.8 кг з рослини", "0.4–0.8 kg per plant", "0.4–0.8 кг с растения"),
      plantTime: t("Квітень або липень на осінь", "April, or July for autumn", "Апрель или июль на осень"),
      maturity: t("60–90 днів", "60–90 days", "60–90 дней"),
      watering: t("Рівномірно, любить вологу", "Evenly, likes moisture", "Равномерно, любит влагу"),
      soil: t("Родючий, pH 6.0–7.0", "Fertile, pH 6.0–7.0", "Плодородный, pH 6.0–7.0"),
      climate: t("Прохолодно, 15–20 °C", "Cool, 15–20 °C", "Прохладно, 15–20 °C"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1 см", "1 cm", "1 см"),
      seedRate: t("4–6 рослин / м²", "4–6 plants / m²", "4–6 растений / м²"),
      seedlings: t("Розсада 35–45 днів", "35–45 day seedlings", "Рассада 35–45 дней"),
      companions: t("Цибуля, салат, кріп", "Onion, lettuce, dill", "Лук, салат, укроп"),
      pests: t("Попелиця, капустяна міль", "Aphids, cabbage moth", "Тля, капустная моль"),
      fertilizer: t("Азот і бор, без перегодівлі", "Nitrogen and boron, do not overfeed", "Азот и бор, без перекорма"),
    },
    {
      varietyType: t("Калбрезські гібриди, бічні пагони", "Calabrese hybrids, side shoots", "Кальбрезские гибриды, боковые побеги"),
      pollination: t("Перехресне, комахи", "Cross-pollinated by insects", "Перекрёстное, насекомые"),
      habit: t("Стебло з центральною головкою", "Stem with a central head", "Стебель с центральной головкой"),
      ploidy: t("Диплоїд, 2n = 18", "Diploid, 2n = 18", "Диплоид, 2n = 18"),
      traits: t("Зелені бутони, після зрізу — бічні головки", "Green buds; side heads after cutting", "Зелёные бутоны, после среза — боковые головки"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Суцвіття, стебло, пагони", "Heads, stem, shoots", "Соцветия, стебель, побеги"),
      culinary: t("На пару, салати, заморозка", "Steaming, salads, freezing", "На пару, салаты, заморозка"),
      harvest: t("До розкриття бутонів", "Before buds open", "До раскрытия бутонов"),
      storage: t("Коротко в холодильнику", "Briefly in the fridge", "Кратко в холодильнике"),
    }
  ),
  kb_species_brassica_oleracea_botrytis: veg(
    "/plants/cauliflower.svg",
    {
      family: brassicaceae,
      genus: t("Капуста (Brassica)", "Brassica", "Капуста (Brassica)"),
      species: t("Brassica oleracea var. botrytis", "Brassica oleracea var. botrytis", "Brassica oleracea var. botrytis"),
      lifeCycle: t("Дворічна, як однорічна", "Biennial grown as an annual", "Двулетняя, как однолетняя"),
      origin: t("Середземномор’я", "Mediterranean", "Средиземноморье"),
      summary: t("Цвітна капуста з ніжною головкою суцвіть.", "Cauliflower with a tender curd.", "Цветная капуста с нежной головкой соцветий."),
    },
    {
      yield: t("0.5–1.2 кг з рослини", "0.5–1.2 kg per plant", "0.5–1.2 кг с растения"),
      plantTime: t("Квітень–травень, липень на осінь", "April–May, July for autumn", "Апрель–май, июль на осень"),
      maturity: t("70–100 днів", "70–100 days", "70–100 дней"),
      watering: t("Постійно волого", "Keep evenly moist", "Постоянно влажно"),
      soil: t("Родючий, рівномірно вологий", "Fertile, evenly moist", "Плодородный, равномерно влажный"),
      climate: t("Прохолодно, без різкої спеки", "Cool, no sudden heat", "Прохладно, без резкой жары"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1 см", "1 cm", "1 см"),
      seedRate: t("4 рослини / м²", "4 plants / m²", "4 растения / м²"),
      seedlings: t("Розсада 40–50 днів", "40–50 day seedlings", "Рассада 40–50 дней"),
      companions: t("Селера, цибуля, кріп", "Celery, onion, dill", "Сельдерей, лук, укроп"),
      pests: t("Блішки, міль, кила", "Flea beetles, moth, clubroot", "Блошки, моль, кила"),
      fertilizer: t("Бор і молібден, рівний азот", "Boron and molybdenum, steady nitrogen", "Бор и молибден, ровный азот"),
    },
    {
      varietyType: t("Білі, кольорові, романеско", "White, coloured, romanesco", "Белые, цветные, романеско"),
      pollination: t("Перехресне, комахи", "Cross-pollinated by insects", "Перекрёстное, насекомые"),
      habit: t("Розетка, головка в центрі", "Rosette with a central curd", "Розетка, головка в центре"),
      ploidy: t("Диплоїд, 2n = 18", "Diploid, 2n = 18", "Диплоид, 2n = 18"),
      traits: t("Головку притіняють листям від сонця", "Blanch the curd with leaves", "Головку притеняют листьями от солнца"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Головка суцвіть", "Curd", "Головка соцветий"),
      culinary: t("Варіння, запікання, суп", "Boiling, roasting, soup", "Варка, запекание, суп"),
      harvest: t("Поки головка щільна й біла", "While the curd is tight and white", "Пока головка плотная и белая"),
      storage: t("Коротко в холоді", "Briefly chilled", "Кратко в холоде"),
    }
  ),
  kb_species_brassica_oleracea_gongylodes: veg(
    "/plants/kohlrabi.svg",
    {
      family: brassicaceae,
      genus: t("Капуста (Brassica)", "Brassica", "Капуста (Brassica)"),
      species: t("Brassica oleracea var. gongylodes", "Brassica oleracea var. gongylodes", "Brassica oleracea var. gongylodes"),
      lifeCycle: t("Дворічна, як однорічна", "Biennial grown as an annual", "Двулетняя, как однолетняя"),
      origin: t("Північна Європа", "Northern Europe", "Северная Европа"),
      summary: t("Кольрабі зі стебловим «яблуком» над ґрунтом.", "Kohlrabi with a swollen stem above ground.", "Кольраби со стеблевым «яблоком» над почвой."),
    },
    {
      yield: t("0.3–0.6 кг з рослини", "0.3–0.6 kg per plant", "0.3–0.6 кг с растения"),
      plantTime: t("Квітень–липень", "April–July", "Апрель–июль"),
      maturity: t("50–70 днів", "50–70 days", "50–70 дней"),
      watering: t("Рівномірно, інакше дерев’яніє", "Evenly, or it turns woody", "Равномерно, иначе деревенеет"),
      soil: t("Легкий родючий", "Light, fertile", "Лёгкий плодородный"),
      climate: t("Прохолодно", "Cool", "Прохладно"),
      light: t("Сонце або легка півтінь", "Sun or light shade", "Солнце или лёгкая тень"),
      sowingDepth: t("1 см", "1 cm", "1 см"),
      seedRate: t("9–12 рослин / м²", "9–12 plants / m²", "9–12 растений / м²"),
      seedlings: t("Прямий посів або розсада 30 днів", "Direct sow or 30-day seedlings", "Прямой посев или рассада 30 дней"),
      companions: t("Салат, буряк, огірок", "Lettuce, beet, cucumber", "Салат, свёкла, огурец"),
      pests: t("Блішки, капустяна муха", "Flea beetles, cabbage fly", "Блошки, капустная муха"),
      fertilizer: t("Помірна органіка", "Moderate organics", "Умеренная органика"),
    },
    {
      varietyType: t("Білі й фіолетові ранні сорти", "White and purple early cultivars", "Белые и фиолетовые ранние сорта"),
      pollination: t("Перехресне, комахи", "Cross-pollinated by insects", "Перекрёстное, насекомые"),
      habit: t("Потовщене стебло над ґрунтом", "Swollen stem above soil", "Утолщённый стебель над почвой"),
      ploidy: t("Диплоїд, 2n = 18", "Diploid, 2n = 18", "Диплоид, 2n = 18"),
      traits: t("Соковите «яблуко», молоде листя їстівне", "Juicy stem; young leaves are edible", "Сочное «яблоко», молодые листья съедобны"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Стеблоплід, молоде листя", "Swollen stem, young leaves", "Стеблеплод, молодые листья"),
      culinary: t("Салати, тушкування", "Salads, stewing", "Салаты, тушение"),
      harvest: t("6–8 см, не перерощувати", "6–8 cm, do not overgrow", "6–8 см, не переращивать"),
      storage: t("Коротко в холодильнику", "Briefly in the fridge", "Кратко в холодильнике"),
    }
  ),
  kb_species_daucus_carota: veg(
    "/plants/carrot.svg",
    {
      family: apiaceae,
      genus: t("Морква (Daucus)", "Daucus", "Морковь (Daucus)"),
      species: t("Daucus carota", "Daucus carota", "Daucus carota"),
      lifeCycle: t("Дворічна коренеплідна", "Biennial root crop", "Двулетняя корнеплодная"),
      origin: t("Євразія; столова — селекція", "Eurasia; table types are selected", "Евразия; столовая — селекция"),
      summary: t("Солодкий коренеплід для городу й зберігання.", "Sweet root crop for the garden and storage.", "Сладкий корнеплод для огорода и хранения."),
    },
    {
      yield: t("3–6 кг / м²", "3–6 kg / m²", "3–6 кг / м²"),
      plantTime: t("Березень–червень", "March–June", "Март–июнь"),
      maturity: t("70–120 днів", "70–120 days", "70–120 дней"),
      watering: t("Рівномірно, без кірки", "Evenly, no crust", "Равномерно, без корки"),
      soil: t("Глибокий легкий, без каміння", "Deep and light, no stones", "Глубокий лёгкий, без камней"),
      climate: t("Прохолодно на старті", "Cool at the start", "Прохладно на старте"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1–2 см", "1–2 cm", "1–2 см"),
      seedRate: t("80–120 рослин / м² після проривання", "80–120 plants / m² after thinning", "80–120 растений / м² после прорывки"),
      seedlings: t("Прямий посів, проривати", "Direct sow, then thin", "Прямой посев, прорывать"),
      companions: t("Цибуля, горох, редиска", "Onion, pea, radish", "Лук, горох, редис"),
      pests: t("Морквяна муха", "Carrot fly", "Морковная муха"),
      fertilizer: t("Без свіжого гною", "No fresh manure", "Без свежего навоза"),
    },
    {
      varietyType: t("Нантські, шантане, дайго", "Nantes, Chantenay, Kuroda types", "Нантские, шантане, дайго"),
      pollination: t("Перехресне, комахи, на 2-й рік", "Cross-pollinated by insects in year two", "Перекрёстное, насекомые, на 2-й год"),
      habit: t("Розетка листя, стрижневий корінь", "Leaf rosette with a taproot", "Розетка листьев, стержневой корень"),
      ploidy: t("Диплоїд, 2n = 18", "Diploid, 2n = 18", "Диплоид, 2n = 18"),
      traits: t("Каротин, солодка м’якоть", "Carotene, sweet flesh", "Каротин, сладкая мякоть"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Коренеплід, молоде листя", "Root, young leaves", "Корнеплод, молодые листья"),
      culinary: t("Сира, тушкована, сік", "Raw, stewed, juice", "Сырая, тушёная, сок"),
      harvest: t("За розміром сорту, не тріскати", "At cultivar size, before splitting", "По размеру сорта, не растрескивать"),
      storage: t("Пізні — пісок, 0–2 °C", "Late types in sand, 0–2 °C", "Поздние — песок, 0–2 °C"),
    }
  ),
  kb_species_petroselinum_crispum: veg(
    "/plants/parsley.svg",
    {
      family: apiaceae,
      genus: t("Петрушка (Petroselinum)", "Petroselinum", "Петрушка (Petroselinum)"),
      species: t("Petroselinum crispum", "Petroselinum crispum", "Petroselinum crispum"),
      lifeCycle: t("Дворічна зелень", "Biennial herb", "Двулетняя зелень"),
      origin: t("Середземномор’я", "Mediterranean", "Средиземноморье"),
      summary: t("Листова й коренева петрушка для кухні.", "Leaf and root parsley for the kitchen.", "Листовая и корневая петрушка для кухни."),
    },
    {
      yield: t("Кілька зрізів зелені за сезон", "Several leaf cuts a season", "Несколько срезок зелени за сезон"),
      plantTime: t("Березень–травень", "March–May", "Март–май"),
      maturity: t("70–90 днів до зрізу", "70–90 days to first cut", "70–90 дней до срезки"),
      watering: t("Помірно, ґрунт вологий", "Moderate, keep soil moist", "Умеренно, почва влажная"),
      soil: t("Пухкий, родючий", "Loose, fertile", "Рыхлый, плодородный"),
      climate: t("Прохолодно, тіньовитривала", "Cool, shade-tolerant", "Прохладно, теневыносливая"),
      light: t("Сонце / півтінь", "Sun / partial shade", "Солнце / полутень"),
      sowingDepth: t("1 см", "1 cm", "1 см"),
      seedRate: t("20–30 рослин / м²", "20–30 plants / m²", "20–30 растений / м²"),
      seedlings: t("Прямий посів, насіння сходить довго", "Direct sow; seed is slow", "Прямой посев, семена всходят долго"),
      companions: t("Помідор, морква, цибуля", "Tomato, carrot, onion", "Томат, морковь, лук"),
      pests: t("Секторіоз, попелиця", "Septoria, aphids", "Септориоз, тля"),
      fertilizer: t("Компост навесні", "Compost in spring", "Компост весной"),
    },
    {
      varietyType: t("Листова кучерява, гладка, коренева", "Curly leaf, flat leaf, root types", "Листовая кудрявая, гладкая, корневая"),
      pollination: t("Комахи, на 2-й рік", "Insects, in year two", "Насекомые, на 2-й год"),
      habit: t("Розетка; кореневі — м’ясистий корінь", "Rosette; root types have a fleshy root", "Розетка; корневые — мясистый корень"),
      ploidy: t("Диплоїд, 2n = 22", "Diploid, 2n = 22", "Диплоид, 2n = 22"),
      traits: t("Ефірні олії, аромат апiolу", "Essential oils, apiole aroma", "Эфирные масла, аромат апиола"),
    },
    {
      purpose: t("Пряність, їжа", "Herb, food", "Специя, еда"),
      edibleParts: t("Листя, корінь у кореневих сортів", "Leaves, root in root cultivars", "Листья, корень у корневых сортов"),
      culinary: t("Зелень, бульйони, сушіння", "Garnish, stocks, drying", "Зелень, бульоны, сушка"),
      harvest: t("Зрізати зовнішнє листя", "Cut outer leaves", "Срезать внешние листья"),
      storage: t("Свіжим коротко або сушіння", "Briefly fresh, or dry", "Свежим коротко или сушка"),
    }
  ),
  kb_species_apium_graveolens: veg(
    "/plants/celery.svg",
    {
      family: apiaceae,
      genus: t("Селера (Apium)", "Apium", "Сельдерей (Apium)"),
      species: t("Apium graveolens", "Apium graveolens", "Apium graveolens"),
      lifeCycle: t("Дворічна", "Biennial", "Двулетняя"),
      origin: t("Середземномор’я, болотисті місця", "Mediterranean wetlands", "Средиземноморье, болотистые места"),
      summary: t("Черешкова, листова й коренева селера.", "Stalk, leaf and celeriac types.", "Черешковый, листовой и корневой сельдерей."),
    },
    {
      yield: t("0.5–1 кг з рослини", "0.5–1 kg per plant", "0.5–1 кг с растения"),
      plantTime: t("Травень (розсада)", "May (transplants)", "Май (рассада)"),
      maturity: t("120–180 днів", "120–180 days", "120–180 дней"),
      watering: t("Постійно волого", "Keep constantly moist", "Постоянно влажно"),
      soil: t("Багатий, вологоємний", "Rich, moisture-retentive", "Богатый, влагоёмкий"),
      climate: t("Прохолодно, без посухи", "Cool, no drought", "Прохладно, без засухи"),
      light: t("Сонце / півтінь", "Sun / partial shade", "Солнце / полутень"),
      sowingDepth: t("0.3 см, світло для сходів", "0.3 cm, needs light to germinate", "0.3 см, свет для всходов"),
      seedRate: t("6–9 рослин / м²", "6–9 plants / m²", "6–9 растений / м²"),
      seedlings: t("Розсада 60–70 днів", "60–70 day seedlings", "Рассада 60–70 дней"),
      companions: t("Капуста, цибуля, помідор", "Cabbage, onion, tomato", "Капуста, лук, томат"),
      pests: t("Секторіоз, попелиця", "Septoria, aphids", "Септориоз, тля"),
      fertilizer: t("Азот і калій рівномірно", "Steady nitrogen and potassium", "Азот и калий равномерно"),
    },
    {
      varietyType: t("Черешкова, листова, коренева", "Stalk, leaf, celeriac", "Черешковый, листовой, корневой"),
      pollination: t("Комахи, на 2-й рік", "Insects, in year two", "Насекомые, на 2-й год"),
      habit: t("Черешки або коренеплід", "Stalks or a swollen hypocotyl", "Черешки или корнеплод"),
      ploidy: t("Диплоїд, 2n = 22", "Diploid, 2n = 22", "Диплоид, 2n = 22"),
      traits: t("Сильний аромат, любить вологу", "Strong aroma, needs moisture", "Сильный аромат, любит влагу"),
    },
    {
      purpose: t("Їжа, пряність", "Food, herb", "Еда, специя"),
      edibleParts: t("Черешки, листя, корінь", "Stalks, leaves, root", "Черешки, листья, корень"),
      culinary: t("Салати, супи, соки", "Salads, soups, juices", "Салаты, супы, соки"),
      harvest: t("Черешки — за товщиною; корінь — восени", "Stalks by thickness; root in autumn", "Черешки — по толщине; корень — осенью"),
      storage: t("Корінь у піску, черешки коротко", "Root in sand, stalks briefly", "Корень в песке, черешки кратко"),
    }
  ),
  kb_species_allium_cepa: veg(
    "/plants/onion.svg",
    {
      family: amaryllidaceae,
      genus: t("Цибуля (Allium)", "Allium", "Лук (Allium)"),
      species: t("Allium cepa", "Allium cepa", "Allium cepa"),
      lifeCycle: t("Дворічна цибулинна", "Biennial bulb crop", "Двулетняя луковичная"),
      origin: t("Центральна Азія", "Central Asia", "Центральная Азия"),
      summary: t("Ріпчаста цибуля з сіянки або насіння.", "Bulb onion from sets or seed.", "Репчатый лук из севка или семян."),
    },
    {
      yield: t("3–5 кг / м²", "3–5 kg / m²", "3–5 кг / м²"),
      plantTime: t("Березень–квітень", "March–April", "Март–апрель"),
      maturity: t("90–120 днів", "90–120 days", "90–120 дней"),
      watering: t("До наливу, потім зменшити", "Until bulbs swell, then ease off", "До налива, затем уменьшить"),
      soil: t("Легкий, не кислий", "Light, not acidic", "Лёгкий, не кислый"),
      climate: t("Помірний, світлолюбна", "Temperate, light-loving", "Умеренный, светолюбивая"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("Сіянка 2–3 см", "Sets 2–3 cm", "Севок 2–3 см"),
      seedRate: t("25–40 рослин / м²", "25–40 plants / m²", "25–40 растений / м²"),
      seedlings: t("Сіянка або чорнушка", "Sets or seed", "Севок или чернушка"),
      companions: t("Морква, буряк, салат", "Carrot, beet, lettuce", "Морковь, свёкла, салат"),
      pests: t("Цибулева муха, пероноспороз", "Onion fly, downy mildew", "Луковая муха, пероноспороз"),
      fertilizer: t("Калій і фосфор, без свіжого гною", "Potassium and phosphorus, no fresh manure", "Калий и фосфор, без свежего навоза"),
    },
    {
      varietyType: t("Гострі, напівгострі, салатні", "Pungent, semi-pungent, salad types", "Острые, полуострые, салатные"),
      pollination: t("Комахи, на 2-й рік", "Insects, in year two", "Насекомые, на 2-й год"),
      habit: t("Цибулина з трубчастим листям", "Bulb with tubular leaves", "Луковица с трубчатыми листьями"),
      ploidy: t("Диплоїд, 2n = 16", "Diploid, 2n = 16", "Диплоид, 2n = 16"),
      traits: t("Сухі покривні луски, різний день", "Dry skins, day-length sensitive", "Сухие кроющие чешуи, разный день"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Цибулина, молоде перо", "Bulb, young greens", "Луковица, молодое перо"),
      culinary: t("Сира, смаження, супи", "Raw, frying, soups", "Сырая, жарка, супы"),
      harvest: t("Коли перо лягає", "When tops lodge", "Когда перо полегает"),
      storage: t("Сухо, прохолодно, провітрено", "Dry, cool, ventilated", "Сухо, прохладно, проветриваемо"),
    }
  ),
  kb_species_allium_sativum: veg(
    "/plants/garlic.svg",
    {
      family: amaryllidaceae,
      genus: t("Цибуля (Allium)", "Allium", "Лук (Allium)"),
      species: t("Allium sativum", "Allium sativum", "Allium sativum"),
      lifeCycle: t("Багаторічна, вирощують як однорічну", "Perennial grown as an annual", "Многолетняя, выращивают как однолетнюю"),
      origin: t("Центральна Азія", "Central Asia", "Центральная Азия"),
      summary: t("Часник озимий і ярий із зубків.", "Winter and spring garlic from cloves.", "Чеснок озимый и яровой из зубков."),
    },
    {
      yield: t("0.8–1.5 кг / м²", "0.8–1.5 kg / m²", "0.8–1.5 кг / м²"),
      plantTime: t("Жовтень озимий; березень ярий", "October for winter; March for spring", "Октябрь озимый; март яровой"),
      maturity: t("Озимий — липень; ярий — серпень", "Winter: July; spring: August", "Озимый — июль; яровой — август"),
      watering: t("Навесні волого, перед збором — сухіше", "Moist in spring, drier before harvest", "Весной влажно, перед сбором суше"),
      soil: t("Пухкий, без кислоти", "Loose, not acidic", "Рыхлый, без кислоты"),
      climate: t("Морозостійкий озимий", "Winter types are frost-hardy", "Морозостойкий озимый"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("Зубок 5–7 см", "Clove 5–7 cm", "Зубок 5–7 см"),
      seedRate: t("40–50 рослин / м²", "40–50 plants / m²", "40–50 растений / м²"),
      seedlings: t("Зубки, не насіння", "Cloves, not seed", "Зубки, не семена"),
      companions: t("Морква, полуниця, капуста", "Carrot, strawberry, cabbage", "Морковь, клубника, капуста"),
      pests: t("Нематода, фузаріоз, іржа", "Nematode, fusarium, rust", "Нематода, фузариоз, ржавчина"),
      fertilizer: t("Попіл, калій, без свіжого гною", "Ash, potassium, no fresh manure", "Зола, калий, без свежего навоза"),
    },
    {
      varietyType: t("Стрілкуючі озимі й нестрілкуючі ярі", "Bolting winter and non-bolting spring types", "Стрелкующие озимые и нестрелкующие яровые"),
      pollination: t("Насіння майже не дає, розмноження зубками", "Rarely sets seed, grown from cloves", "Семена почти не даёт, размножение зубками"),
      habit: t("Складна цибулина з зубків", "Compound bulb of cloves", "Сложная луковица из зубков"),
      ploidy: t("Стерильний триплоїд / клони", "Sterile triploid / clones", "Стерильный триплоид / клоны"),
      traits: t("Аліцин, гострий смак", "Allicin, pungent flavour", "Аллицин, острый вкус"),
    },
    {
      purpose: t("Їжа, пряність", "Food, spice", "Еда, специя"),
      edibleParts: t("Зубки, молоде листя, стрілки", "Cloves, young leaves, scapes", "Зубки, молодые листья, стрелки"),
      culinary: t("Сирий, смаження, маринування", "Raw, frying, pickling", "Сырой, жарка, маринование"),
      harvest: t("Коли нижнє листя жовтіє", "When lower leaves yellow", "Когда нижние листья желтеют"),
      storage: t("Сухо, 0–4 °C ярий; озимий — прохолодніше", "Dry; spring at 0–4 °C, winter cooler", "Сухо; яровой 0–4 °C, озимый прохладнее"),
    }
  ),
  kb_species_allium_porrum: veg(
    "/plants/leek.svg",
    {
      family: amaryllidaceae,
      genus: t("Цибуля (Allium)", "Allium", "Лук (Allium)"),
      species: t("Allium porrum", "Allium porrum", "Allium porrum"),
      lifeCycle: t("Дворічна", "Biennial", "Двулетняя"),
      origin: t("Середземномор’я", "Mediterranean", "Средиземноморье"),
      summary: t("Порей з вибіленою ніжкою для осіннього столу.", "Leek with a blanched shaft for autumn.", "Порей с отбелённой ножкой для осеннего стола."),
    },
    {
      yield: t("2–4 кг / м²", "2–4 kg / m²", "2–4 кг / м²"),
      plantTime: t("Травень (розсада)", "May (transplants)", "Май (рассада)"),
      maturity: t("120–180 днів", "120–180 days", "120–180 дней"),
      watering: t("Рівномірно волого", "Evenly moist", "Равномерно влажно"),
      soil: t("Глибокий, родючий", "Deep, fertile", "Глубокий, плодородный"),
      climate: t("Прохолодно, осінні сорти морозостійкі", "Cool; autumn types are frost-hardy", "Прохладно, осенние сорта морозостойки"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1 см", "1 cm", "1 см"),
      seedRate: t("12–20 рослин / м²", "12–20 plants / m²", "12–20 растений / м²"),
      seedlings: t("Розсада 50–60 днів, висадка в борозни", "50–60 day seedlings, plant in trenches", "Рассада 50–60 дней, посадка в борозды"),
      companions: t("Морква, селера, салат", "Carrot, celery, lettuce", "Морковь, сельдерей, салат"),
      pests: t("Цибулева муха, трипси", "Onion fly, thrips", "Луковая муха, трипсы"),
      fertilizer: t("Азот у першій половині", "Nitrogen in the first half", "Азот в первой половине"),
    },
    {
      varietyType: t("Літні й зимові сорти", "Summer and winter cultivars", "Летние и зимние сорта"),
      pollination: t("Комахи, на 2-й рік", "Insects, in year two", "Насекомые, на 2-й год"),
      habit: t("Потовщене несправжнє стебло", "Thickened false stem", "Утолщённый ложный стебель"),
      ploidy: t("Диплоїд, 2n = 32", "Diploid, 2n = 32", "Диплоид, 2n = 32"),
      traits: t("Вибілювання підгортанням", "Blanching by hilling", "Отбеливание окучиванием"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Ніжка, молоде листя", "Shaft, young leaves", "Ножка, молодые листья"),
      culinary: t("Супи, тушкування, вінегрет", "Soups, stewing, vinaigrette", "Супы, тушение, винегрет"),
      harvest: t("За товщиною ніжки, можна зимувати", "By shaft thickness; can overwinter", "По толщине ножки, можно зимовать"),
      storage: t("У ґрунті або піску, прохолодно", "In soil or sand, cool", "В почве или песке, прохладно"),
    }
  ),
  kb_species_lactuca_sativa: veg(
    "/plants/lettuce.svg",
    {
      family: asteraceae,
      genus: t("Латук (Lactuca)", "Lactuca", "Латук (Lactuca)"),
      species: t("Lactuca sativa", "Lactuca sativa", "Lactuca sativa"),
      lifeCycle: t("Однорічна листова", "Annual leafy crop", "Однолетняя листовая"),
      origin: t("Середземномор’я", "Mediterranean", "Средиземноморье"),
      summary: t("Салат листовий і головчастий для прохолоди.", "Leaf and heading lettuce for cool weather.", "Салат листовой и кочанный для прохлады."),
    },
    {
      yield: t("1–3 кг / м²", "1–3 kg / m²", "1–3 кг / м²"),
      plantTime: t("Березень–травень, серпень", "March–May, August", "Март–май, август"),
      maturity: t("30–60 днів", "30–60 days", "30–60 дней"),
      watering: t("Часто, не в’янути", "Often, do not wilt", "Часто, не вянуть"),
      soil: t("Легкий, вологий", "Light, moist", "Лёгкий, влажный"),
      climate: t("Прохолодно, в спеку стрілкує", "Cool; bolts in heat", "Прохладно, в жару стрелкует"),
      light: t("Сонце / півтінь улітку", "Sun / summer partial shade", "Солнце / полутень летом"),
      sowingDepth: t("0.5 см", "0.5 cm", "0.5 см"),
      seedRate: t("16–25 рослин / м²", "16–25 plants / m²", "16–25 растений / м²"),
      seedlings: t("Прямий посів або касети 20 днів", "Direct sow or 20-day plugs", "Прямой посев или кассеты 20 дней"),
      companions: t("Морква, редиска, цибуля", "Carrot, radish, onion", "Морковь, редис, лук"),
      pests: t("Попелиця, слимаки, сіра гниль", "Aphids, slugs, grey mold", "Тля, слизни, серая гниль"),
      fertilizer: t("Легкий азот, без перегодівлі", "Light nitrogen, do not overfeed", "Лёгкий азот, без перекорма"),
    },
    {
      varietyType: t("Лолло, айсберг, ромен, батавія", "Lollo, iceberg, romaine, batavia", "Лолло, айсберг, ромэн, батавия"),
      pollination: t("Самозапильна", "Self-pollinating", "Самоопыляемая"),
      habit: t("Розетка або головка", "Rosette or head", "Розетка или кочан"),
      ploidy: t("Диплоїд, 2n = 18", "Diploid, 2n = 18", "Диплоид, 2n = 18"),
      traits: t("Молочний сік, стрілкування в спеку", "Milky sap, bolts in heat", "Млечный сок, стрелкование в жару"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Листя, головка", "Leaves, head", "Листья, кочан"),
      culinary: t("Салати, сендвічі", "Salads, sandwiches", "Салаты, сэндвичи"),
      harvest: t("До стрілки, зрізати вранці", "Before bolting, cut in the morning", "До стрелки, срезать утром"),
      storage: t("Коротко, високо вологість", "Briefly, high humidity", "Кратко, высокая влажность"),
    }
  ),
  kb_species_spinacia_oleracea: veg(
    "/plants/spinach.svg",
    {
      family: amaranthaceae,
      genus: t("Шпинат (Spinacia)", "Spinacia", "Шпинат (Spinacia)"),
      species: t("Spinacia oleracea", "Spinacia oleracea", "Spinacia oleracea"),
      lifeCycle: t("Однорічна листова", "Annual leafy crop", "Однолетняя листовая"),
      origin: t("Персія, Центральна Азія", "Persia, Central Asia", "Персия, Центральная Азия"),
      summary: t("Швидка зелень для весни й осені.", "Fast greens for spring and autumn.", "Быстрая зелень для весны и осени."),
    },
    {
      yield: t("1–2 кг / м²", "1–2 kg / m²", "1–2 кг / м²"),
      plantTime: t("Березень–квітень, серпень–вересень", "March–April, August–September", "Март–апрель, август–сентябрь"),
      maturity: t("30–45 днів", "30–45 days", "30–45 дней"),
      watering: t("Регулярно, ґрунт вологий", "Regularly, keep soil moist", "Регулярно, почва влажная"),
      soil: t("Родючий, pH 6.5–7.5", "Fertile, pH 6.5–7.5", "Плодородный, pH 6.5–7.5"),
      climate: t("Прохолодно, в спеку стрілкує", "Cool; bolts in heat", "Прохладно, в жару стрелкует"),
      light: t("Сонце / півтінь", "Sun / partial shade", "Солнце / полутень"),
      sowingDepth: t("2 см", "2 cm", "2 см"),
      seedRate: t("40–60 рослин / м²", "40–60 plants / m²", "40–60 растений / м²"),
      seedlings: t("Прямий посів", "Direct sow", "Прямой посев"),
      companions: t("Полуниця, горох, капуста", "Strawberry, pea, cabbage", "Клубника, горох, капуста"),
      pests: t("Пероноспороз, попелиця", "Downy mildew, aphids", "Пероноспороз, тля"),
      fertilizer: t("Азот помірно", "Moderate nitrogen", "Азот умеренно"),
    },
    {
      varietyType: t("Гладке й пухирчасте листя", "Smooth and savoy-leaf types", "Гладкий и пузырчатый лист"),
      pollination: t("Вітер, роздільностатева", "Wind, dioecious", "Ветер, раздельнополая"),
      habit: t("Розетка листя", "Leaf rosette", "Розетка листьев"),
      ploidy: t("Диплоїд, 2n = 12", "Diploid, 2n = 12", "Диплоид, 2n = 12"),
      traits: t("Оксалат, ніжне листя", "Oxalates, tender leaves", "Оксалат, нежные листья"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Листя", "Leaves", "Листья"),
      culinary: t("Салати, тушкування, заморозка", "Salads, stewing, freezing", "Салаты, тушение, заморозка"),
      harvest: t("До стрілки, зріз або виривання", "Before bolting, cut or pull", "До стрелки, срез или вырывание"),
      storage: t("Дуже коротко свіжим", "Very briefly fresh", "Очень кратко свежим"),
    }
  ),
  kb_species_pisum_sativum: veg(
    "/plants/pea.svg",
    {
      family: fabaceae,
      genus: t("Горох (Pisum)", "Pisum", "Горох (Pisum)"),
      species: t("Pisum sativum", "Pisum sativum", "Pisum sativum"),
      lifeCycle: t("Однорічна зернобобова", "Annual pulse", "Однолетняя зернобобовая"),
      origin: t("Близький Схід", "Near East", "Ближний Восток"),
      summary: t("Горох мозковий, лущильний і цукровий.", "Garden, shelling and snap peas.", "Горох мозговой, лущильный и сахарный."),
    },
    {
      yield: t("1–2 кг зеленого горошку / м²", "1–2 kg green peas / m²", "1–2 кг зелёного горошка / м²"),
      plantTime: t("Березень–квітень", "March–April", "Март–апрель"),
      maturity: t("50–70 днів", "50–70 days", "50–70 дней"),
      watering: t("Волого в цвітіння й налив", "Moist at flowering and fill", "Влажно в цветение и налив"),
      soil: t("Легкий, не кислий", "Light, not acidic", "Лёгкий, не кислый"),
      climate: t("Прохолодно, не любить спеку", "Cool, dislikes heat", "Прохладно, не любит жару"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("3–4 см", "3–4 cm", "3–4 см"),
      seedRate: t("60–80 рослин / м²", "60–80 plants / m²", "60–80 растений / м²"),
      seedlings: t("Прямий посів, опора для високих", "Direct sow; trellis tall types", "Прямой посев, опора для высоких"),
      companions: t("Морква, редиска, кукурудза", "Carrot, radish, corn", "Морковь, редис, кукуруза"),
      pests: t("Попелиця, борошниста роса", "Aphids, powdery mildew", "Тля, мучнистая роса"),
      fertilizer: t("Без надлишку азоту, любить фосфор", "Avoid excess nitrogen, likes phosphorus", "Без избытка азота, любит фосфор"),
    },
    {
      varietyType: t("Лущильні, мозкові, цукрові", "Shelling, marrowfat, snap types", "Лущильные, мозговые, сахарные"),
      pollination: t("Самозапильна", "Self-pollinating", "Самоопыляемая"),
      habit: t("Ліана з вусиками", "Vine with tendrils", "Лиана с усиками"),
      ploidy: t("Диплоїд, 2n = 14", "Diploid, 2n = 14", "Диплоид, 2n = 14"),
      traits: t("Азотфіксація, солодке насіння", "Nitrogen fixation, sweet seed", "Азотфиксация, сладкие семена"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Насіння, у цукрових — стручок", "Seed; snap types include the pod", "Семена, у сахарных — стручок"),
      culinary: t("Свіжий, суп, заморозка", "Fresh, soup, freezing", "Свежий, суп, заморозка"),
      harvest: t("Молочна стиглість, регулярно", "Milk-ripe, regularly", "Молочная спелость, регулярно"),
      storage: t("Краще одразу їсти або заморозити", "Eat or freeze soon", "Лучше сразу есть или заморозить"),
    }
  ),
  kb_species_phaseolus_vulgaris: veg(
    "/plants/bean.svg",
    {
      family: fabaceae,
      genus: t("Квасоля (Phaseolus)", "Phaseolus", "Фасоль (Phaseolus)"),
      species: t("Phaseolus vulgaris", "Phaseolus vulgaris", "Phaseolus vulgaris"),
      lifeCycle: t("Однорічна зернобобова", "Annual pulse", "Однолетняя зернобобовая"),
      origin: t("Центральна Америка", "Central America", "Центральная Америка"),
      summary: t("Спаржева й зернова квасоля для теплого городу.", "Snap and dry beans for a warm garden.", "Спаржевая и зерновая фасоль для тёплого огорода."),
    },
    {
      yield: t("1.5–3 кг зелених стручків / м²", "1.5–3 kg green pods / m²", "1.5–3 кг зелёных стручков / м²"),
      plantTime: t("Травень, ґрунт >12 °C", "May, soil above 12 °C", "Май, почва >12 °C"),
      maturity: t("50–70 днів до лопатки", "50–70 days to snap harvest", "50–70 дней до лопатки"),
      watering: t("Рівномірно в цвітіння", "Evenly while flowering", "Равномерно в цветение"),
      soil: t("Теплий, дренований", "Warm, drained", "Тёплый, дренированный"),
      climate: t("Тепло, без заморозків", "Warm, frost-free", "Тепло, без заморозков"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("3–4 см", "3–4 cm", "3–4 см"),
      seedRate: t("Кущова 12–16 / м²; витка — з опорою", "Bush 12–16 / m²; pole types need support", "Кустовая 12–16 / м²; вьющаяся — с опорой"),
      seedlings: t("Прямий посів", "Direct sow", "Прямой посев"),
      companions: t("Кукурудза, гарбуз, огірок", "Corn, pumpkin, cucumber", "Кукуруза, тыква, огурец"),
      pests: t("Попелиця, антракноз", "Aphids, anthracnose", "Тля, антракноз"),
      fertilizer: t("Мало азоту, калій у плодоношення", "Little nitrogen, potassium while fruiting", "Мало азота, калий в плодоношение"),
    },
    {
      varietyType: t("Кущові й виткі; спаржеві й зернові", "Bush and pole; snap and dry", "Кустовые и вьющиеся; спаржевые и зерновые"),
      pollination: t("Самозапильна", "Self-pollinating", "Самоопыляемая"),
      habit: t("Кущ або ліана", "Bush or vine", "Куст или лиана"),
      ploidy: t("Диплоїд, 2n = 22", "Diploid, 2n = 22", "Диплоид, 2n = 22"),
      traits: t("Азотфіксація, ніжні лопатки без пергаменту", "Nitrogen fixation, tender stringless pods", "Азотфиксация, нежные лопатки без пергамента"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Стручки, насіння", "Pods, seed", "Стручки, семена"),
      culinary: t("Тушкування, заморозка, сухе зерно", "Stewing, freezing, dry beans", "Тушение, заморозка, сухое зерно"),
      harvest: t("Лопатка до ниток; зерно — на суху", "Snap before strings; dry when pods rattle", "Лопатка до ниток; зерно — на сухую"),
      storage: t("Зелені — коротко; зерно — сухо", "Green briefly; dry beans stored dry", "Зелёные — кратко; зерно — сухо"),
    }
  ),
  kb_species_beta_vulgaris: veg(
    "/plants/beet.svg",
    {
      family: amaranthaceae,
      genus: t("Буряк (Beta)", "Beta", "Свёкла (Beta)"),
      species: t("Beta vulgaris", "Beta vulgaris", "Beta vulgaris"),
      lifeCycle: t("Дворічна коренеплідна", "Biennial root crop", "Двулетняя корнеплодная"),
      origin: t("Середземномор’я", "Mediterranean", "Средиземноморье"),
      summary: t("Столовий буряк для борщу й салатів.", "Garden beet for borscht and salads.", "Столовая свёкла для борща и салатов."),
    },
    {
      yield: t("3–5 кг / м²", "3–5 kg / m²", "3–5 кг / м²"),
      plantTime: t("Квітень–червень", "April–June", "Апрель–июнь"),
      maturity: t("70–100 днів", "70–100 days", "70–100 дней"),
      watering: t("Рівномірно, без розтріскування", "Evenly, to avoid splitting", "Равномерно, без растрескивания"),
      soil: t("Пухкий, pH 6.5–7.5", "Loose, pH 6.5–7.5", "Рыхлый, pH 6.5–7.5"),
      climate: t("Помірний", "Temperate", "Умеренный"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("2–3 см", "2–3 cm", "2–3 см"),
      seedRate: t("25–40 рослин / м²", "25–40 plants / m²", "25–40 растений / м²"),
      seedlings: t("Прямий посів, клубочки проривати", "Direct sow, thin clustered seed", "Прямой посев, клубочки прорывать"),
      companions: t("Цибуля, капуста, салат", "Onion, cabbage, lettuce", "Лук, капуста, салат"),
      pests: t("Попелиця, церкоспороз", "Aphids, cercospora", "Тля, церкоспороз"),
      fertilizer: t("Бор, без свіжого гною", "Boron, no fresh manure", "Бор, без свежего навоза"),
    },
    {
      varietyType: t("Круглі й циліндричні столові", "Round and cylindrical table types", "Круглые и цилиндрические столовые"),
      pollination: t("Вітер, на 2-й рік", "Wind, in year two", "Ветер, на 2-й год"),
      habit: t("Коренеплід і черешкове листя", "Root with petiolate leaves", "Корнеплод и черешковые листья"),
      ploidy: t("Диплоїд / триплоїд гібриди", "Diploid / triploid hybrids", "Диплоид / триплоид гибриды"),
      traits: t("Беталаїни, солодка м’якоть", "Betalains, sweet flesh", "Беталаины, сладкая мякоть"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Коренеплід, молоде листя", "Root, young leaves", "Корнеплод, молодые листья"),
      culinary: t("Борщ, салат, маринування", "Borscht, salad, pickling", "Борщ, салат, маринование"),
      harvest: t("5–10 см, не перерощувати", "5–10 cm, do not overgrow", "5–10 см, не переращивать"),
      storage: t("Пісок, 0–2 °C, гичку зрізати", "Sand, 0–2 °C, tops trimmed", "Песок, 0–2 °C, ботву срезать"),
    }
  ),
  kb_species_zea_mays: veg(
    "/plants/corn.svg",
    {
      family: poaceae,
      genus: t("Кукурудза (Zea)", "Zea", "Кукуруза (Zea)"),
      species: t("Zea mays", "Zea mays", "Zea mays"),
      lifeCycle: t("Однорічна", "Annual", "Однолетняя"),
      origin: t("Мезоамерика", "Mesoamerica", "Мезоамерика"),
      summary: t("Цукрова кукурудза для молочної стиглості.", "Sweet corn harvested at milk stage.", "Сахарная кукуруза для молочной спелости."),
    },
    {
      yield: t("2–4 качани з рослини", "2–4 ears per plant", "2–4 початка с растения"),
      plantTime: t("Травень, ґрунт >12 °C", "May, soil above 12 °C", "Май, почва >12 °C"),
      maturity: t("70–90 днів", "70–90 days", "70–90 дней"),
      watering: t("Рясно в викидання волоті й налив", "Heavy at tasseling and fill", "Обильно при вымётывании и наливе"),
      soil: t("Родючий, теплий", "Fertile, warm", "Плодородный, тёплый"),
      climate: t("Тепло, без заморозків", "Warm, frost-free", "Тепло, без заморозков"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("4–5 см", "4–5 cm", "4–5 см"),
      seedRate: t("6–8 рослин / м², блоком для запилення", "6–8 plants / m², in a block for pollination", "6–8 растений / м², блоком для опыления"),
      seedlings: t("Прямий посів", "Direct sow", "Прямой посев"),
      companions: t("Квасоля, гарбуз, огірок", "Bean, pumpkin, cucumber", "Фасоль, тыква, огурец"),
      pests: t("Попелиця, кукурудзяний метелик", "Aphids, corn borer", "Тля, кукурузный мотылёк"),
      fertilizer: t("Азот до викидання волоті", "Nitrogen until tasseling", "Азот до вымётывания метёлки"),
    },
    {
      varietyType: t("Цукрові su / sh2 гібриди", "Sweet su / sh2 hybrids", "Сахарные su / sh2 гибриды"),
      pollination: t("Вітер, садити квадратом", "Wind; plant in a block", "Ветер, сажать квадратом"),
      habit: t("Високе стебло, качани в пазухах", "Tall stem, ears in leaf axils", "Высокий стебель, початки в пазухах"),
      ploidy: t("Диплоїд, 2n = 20", "Diploid, 2n = 20", "Диплоид, 2n = 20"),
      traits: t("Солодке зерно в молочній стиглості", "Sweet grain at milk stage", "Сладкое зерно в молочной спелости"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Зерно качана", "Ear grain", "Зерно початка"),
      culinary: t("Варіння, гриль, заморозка", "Boiling, grilling, freezing", "Варка, гриль, заморозка"),
      harvest: t("Молочна стиглість, шовк коричневіє", "Milk stage, silk browns", "Молочная спелость, шёлк коричневеет"),
      storage: t("Одразу варити або заморозити", "Cook or freeze at once", "Сразу варить или заморозить"),
    }
  ),
  kb_species_pastinaca_sativa: veg(
    "/plants/parsnip.svg",
    {
      family: apiaceae,
      genus: t("Пастернак (Pastinaca)", "Pastinaca", "Пастернак (Pastinaca)"),
      species: t("Pastinaca sativa", "Pastinaca sativa", "Pastinaca sativa"),
      lifeCycle: t("Дворічна коренеплідна", "Biennial root crop", "Двулетняя корнеплодная"),
      origin: t("Євразія", "Eurasia", "Евразия"),
      summary: t("Солодкий білий коренеплід, що набирає смак після холоду.", "Sweet white root that sweetens after frost.", "Сладкий белый корнеплод, набирает вкус после холода."),
    },
    {
      yield: t("2–4 кг / м²", "2–4 kg / m²", "2–4 кг / м²"),
      plantTime: t("Березень–квітень", "March–April", "Март–апрель"),
      maturity: t("120–150 днів", "120–150 days", "120–150 дней"),
      watering: t("Рівномірно на старті", "Evenly at the start", "Равномерно на старте"),
      soil: t("Глибокий легкий, без каміння", "Deep and light, no stones", "Глубокий лёгкий, без камней"),
      climate: t("Прохолодно, морозостійкий корінь", "Cool; the root is frost-hardy", "Прохладно, морозостойкий корень"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1.5–2 см", "1.5–2 cm", "1.5–2 см"),
      seedRate: t("20–30 рослин / м²", "20–30 plants / m²", "20–30 растений / м²"),
      seedlings: t("Прямий посів свіжим насінням", "Direct sow with fresh seed", "Прямой посев свежими семенами"),
      companions: t("Цибуля, редиска, салат", "Onion, radish, lettuce", "Лук, редис, салат"),
      pests: t("Морквяна муха, септоріоз", "Carrot fly, septoria", "Морковная муха, септориоз"),
      fertilizer: t("Без свіжого гною", "No fresh manure", "Без свежего навоза"),
    },
    {
      varietyType: t("Короткі й довгі коренеплоди", "Short and long-rooted types", "Короткие и длинные корнеплоды"),
      pollination: t("Комахи, на 2-й рік", "Insects, in year two", "Насекомые, на 2-й год"),
      habit: t("Стрижневий корінь, розетка", "Taproot with a leaf rosette", "Стержневой корень, розетка"),
      ploidy: t("Диплоїд, 2n = 22", "Diploid, 2n = 22", "Диплоид, 2n = 22"),
      traits: t("Після морозу солодшає", "Sweetens after frost", "После мороза слаще"),
    },
    {
      purpose: t("Їжа", "Food", "Еда"),
      edibleParts: t("Коренеплід", "Root", "Корнеплод"),
      culinary: t("Запікання, пюре, супи", "Roasting, mash, soups", "Запекание, пюре, супы"),
      harvest: t("Після перших приморозків", "After first frosts", "После первых заморозков"),
      storage: t("У ґрунті або піску, 0–1 °C", "In soil or sand, 0–1 °C", "В почве или песке, 0–1 °C"),
    }
  ),
  kb_species_anethum_graveolens: veg(
    "/plants/dill.svg",
    {
      family: apiaceae,
      genus: t("Кріп (Anethum)", "Anethum", "Укроп (Anethum)"),
      species: t("Anethum graveolens", "Anethum graveolens", "Anethum graveolens"),
      lifeCycle: t("Однорічна пряна зелень", "Annual culinary herb", "Однолетняя пряная зелень"),
      origin: t("Середземномор’я, Західна Азія", "Mediterranean, West Asia", "Средиземноморье, Западная Азия"),
      summary: t("Кріп на зелень і зонтики для засолювання.", "Dill for greens and pickling umbels.", "Укроп на зелень и зонтики для засолки."),
    },
    {
      yield: t("Кілька зрізів або зонтики на насіння", "Several cuts, or umbels for seed", "Несколько срезок или зонтики на семена"),
      plantTime: t("Квітень–липень, сіяти хвилями", "April–July, sow in waves", "Апрель–июль, сеять волнами"),
      maturity: t("30–40 днів на зелень", "30–40 days to greens", "30–40 дней на зелень"),
      watering: t("Помірно", "Moderate", "Умеренно"),
      soil: t("Легкий, без кірки", "Light, no crust", "Лёгкий, без корки"),
      climate: t("Прохолодно–помірно", "Cool to temperate", "Прохладно–умеренно"),
      light: t("Повне сонце", "Full sun", "Полное солнце"),
      sowingDepth: t("1–1.5 см", "1–1.5 cm", "1–1.5 см"),
      seedRate: t("Посів рядком, не загущувати", "Row sowing, do not crowd", "Посев рядком, не загущать"),
      seedlings: t("Прямий посів, погано пересаджується", "Direct sow, dislikes transplanting", "Прямой посев, плохо пересаживается"),
      companions: t("Огірок, капуста, салат", "Cucumber, cabbage, lettuce", "Огурец, капуста, салат"),
      pests: t("Попелиця, борошниста роса", "Aphids, powdery mildew", "Тля, мучнистая роса"),
      fertilizer: t("Легка органіка", "Light organics", "Лёгкая органика"),
    },
    {
      varietyType: t("На зелень і на зонтик", "Leaf types and umbel types", "На зелень и на зонтик"),
      pollination: t("Комахи", "Insect-pollinated", "Насекомые"),
      habit: t("Пряме стебло, зонтичне суцвіття", "Upright stem with an umbel", "Прямой стебель, зонтичное соцветие"),
      ploidy: t("Диплоїд, 2n = 22", "Diploid, 2n = 22", "Диплоид, 2n = 22"),
      traits: t("Ефірні олії, аромат карвону", "Essential oils, carvone aroma", "Эфирные масла, аромат карвона"),
    },
    {
      purpose: t("Пряність, їжа", "Herb, food", "Специя, еда"),
      edibleParts: t("Листя, стебло, насіння", "Leaves, stem, seed", "Листья, стебель, семена"),
      culinary: t("Огірки, риба, салати, засолювання", "Cucumbers, fish, salads, pickling", "Огурцы, рыба, салаты, засолка"),
      harvest: t("Зелень до цвітіння; зонтики — у молочній стиглості насіння", "Greens before flowering; umbels at milk-ripe seed", "Зелень до цветения; зонтики — в молочной спелости семян"),
      storage: t("Сушіння або заморозка", "Dry or freeze", "Сушка или заморозка"),
    }
  ),
}
